### ISSUE TITLE
Can't line up the buttons at the bottom of the page

### ISSUE THREAD

**Issue by Thebeerz** [Thebeerz/modularity-mindfulness#1]
![Screen Shot 2020-09-23 at 11 06 27 AM](https://user-images.githubusercontent.com/55193140/94031846-5070b080-fd8d-11ea-9f2c-62a83c5a366a.png)

I tried to look at cheatsheets but couldn't force buttons to the end of page
@HannahDelaney

**Comment by HannahDelaney** [comment]
So you want to be able to space the content out evenly within the figures. If you enable `display: flex;`, you'll be able to justify the content so they space out between the child elements.

Try adding at the mq:
```
  figure {
    display: flex;
    justify-content: space-between;
    flex-direction: column;
  }
```

You'll also need to make sure you specify that the direction is down the column, otherwise you'll get some very wacky results!
